---
name: plan-c
namespace: demo
scm: git@github.com:uktrade/ci-pipeline.git
environments:
  - environment: dev
    type: heroku
    app: project-fe-dev
    vars:
      - REDIS: redis://redis:6379
      - ES: es://es:9200
    secrets: true
    run:
      - "cat ${WORKSPACE}/env"
      - "env | sort"
      - "echo hello\ world"
  - environment: staging
    type: s3
    app: bucket.eu-west-2
    vars:
      - REDIS: redis://redis:6379
    secrets: false
    run:
      - "/bin/bash"
      - "docker run"
  - environment: production
    type: gds
    app: project-prod/fe
    vars:
      - REDIS: redis://redis:6379
    secrets: false
    run:
      - "/bin/bash"
      - "docker run"
