---
name: plan-c
namespace: demo
scm: git@github.com:cloudfoundry-samples/cf-sample-app-nodejs.git
environments:
  - environment: dev
    type: gds
    app: sandbox/cf-nodejs
    vars:
      - REDIS: redis://redis:6379
      - ES: es://es:9200
    secrets: true
    run:
      - "ls -al ${WORKSPACE}"
      - "env | sort"
      - "echo hello\ world"
  - environment: staging
    type: s3
    app: bucket.eu-west-2
    vars:
      - REDIS: redis://redis:6379
    secrets: false
    run:
      - "/bin/bash"
      - "docker run"
  - environment: production
    type: gds
    app: project-prod/fe
    vars:
      - REDIS: redis://redis:6379
    secrets: false
    run:
      - "/bin/bash"
      - "docker run"
