---
name: cert-monitor
namespace: webops
scm: git@github.com:uktrade/cert_monitor.git
environments:
  - environment: production
    type: gds
    app: dit-services/webops/cert-monitor-production
    vars: 
      - KEY: VALUE
    secrets: false
    run:
      - "true"