---
name: contact-ukti
namespace: exopps
scm: git@github.com:uktrade/contact-ukti.git
environments:
  - environment: dev
    type: gds
    app: dev-exopps/contact-ukti-dev
    vars:
      - LOG_LEVEL: debug
      - EMAIL_HOST: email-smtp.eu-west-1.amazonaws.com
      - EMAIL_PORT: 587
      - STUNNEL_ENABLED: true
      - REDIS_USE_TLS: true
      - REDIS_USE_SENTINEL: true
      - USE_AUTH: false
      - REDIS_HOST: contactukti-redis.gds-dev.uktrade.io
      - REDIS_URL: contactukti-redis.gds-dev.uktrade.io
      - REDIS_PORT: 26379
      - ZENDESK_URL: https://staging-uktrade.zendesk.com/api/v2
      - ZENDESK_TAG: contact-dit-staging
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dev-exopps/contact-ukti
    vars:
      - NODE_MODULES_CACHE: false
      - NPM_CONFIG_PRODUCTION: false
      - LOG_LEVEL: debug
      - EMAIL_HOST: email-smtp.eu-west-1.amazonaws.com
      - EMAIL_PORT: 587
      - STUNNEL_ENABLED: true
      - REDIS_USE_SENTINEL: true
      - USE_AUTH: false
      - REDIS_HOST: contactukti-redis.gds-dev.uktrade.io
      - REDIS_URL: contactukti-redis.gds-dev.uktrade.io
      - REDIS_PORT: 26379
      - ZENDESK_URL: https://staging-uktrade.zendesk.com/api/v2
      - ZENDESK_TAG: contact-dit-staging
    secrets: false
    run:
      - "true"
