name: digital-workspace
namespace: intranet
scm: git@github.com:uktrade/digital-workspace.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-peoplefinder/digital-workspace-dev
    vars:
      - API: 'digital-workspace-dev.cloudapps.digital/'
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-peoplefinder/digital-workspace-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/peoplefinder/digital-workspace
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
