---
name: directory-api
namespace: directory
scm: git@github.com:uktrade/directory-api.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-directory/directory-api-dev
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-directory/directory-api-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/directory/directory-api
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
---
name: directory-celery_beat_scheduler
namespace: directory
scm: git@github.com:uktrade/directory-api.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-directory/ddirectory-celery_beat_scheduler-dev
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-directory/directory-celery_beat_scheduler-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/directory/directory-celery_beat_scheduler
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"

