---
name: directory-sso-profile
namespace: directory
scm: git@github.com:uktrade/directory-sso-profile.git
environments:
  - environment: dev
    type: gds
    app: dev-directory/directory-sso-profile
    vars:
      - API_CLIENT_BASE_URL: 'http://directory-sso-profile-dev.herokuapp.com/'
    secrets: true
    run:
      - "true"
