---
name: directory-ui-supplier
namespace: directory
scm: git@github.com:uktrade/directory-ui-supplier.git
environments:
  - environment: dev
    type: gds
    app: dit-services/dev-directory/directory-ui-supplier
    vars:
      - API: 'api'
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/dev-directory/directory-ui-supplier
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
