---
name: directory-api
namespace: directory
scm: git@github.com:uktrade/directory-api.git
environments:
  - environment: dev
    type: gds
    app: dev-directory/directory-api
    vars:
      - API_CLIENT_BASE_URL: 'http://directory-api-dev.herokuapp.com/'
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
