---
name: directory-sso
namespace: directory
scm: git@github.com:uktrade/directory-sso.git
environments:
  - environment: dev
    type: gds
    app: dit-services/dev-directory/directory-sso
    vars:
      - url_Service: 'https'
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/dev-directory/directory-sso
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
