---
name: peoplefinder
namespace: peoplefinder
scm: git@github.com:uktrade/peoplefinder.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-peoplefinder/peoplefinder-dev
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-peoplefinder/peoplefinder-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/peoplefinder/peoplefinder
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
